import json

loadFactor = {
    'Ethiopian Airlines': 0.82,
    'EgyptAir': 0.78,
    'South African Airways': 0.75,
    'Kenya Airways': 0.80,
    'Royal Air Maroc': 0.79,
    'Air Algérie': 0.72,
    'Tunisair': 0.70,
    'Air Mauritius': 0.77,
    'Air Peace': 0.68,
    'RwandAir': 0.74,
    'Air Tanzania': 0.70,
    'FlySafair': 0.82,
    'Africa World Airlines': 0.67,
    'Libyan Airlines': 0.65,
    'Air Côte d\'Ivoire': 0.73,
    'TAAG Angola Airlines': 0.71,
    'Air Senegal': 0.72,
    'Airlink': 0.83,
    'Fastjet': 0.69,
    'Nile Air': 0.71,
    'American Airlines': 0.849,
    'Delta Air Lines': 0.85,
    'United Airlines': 0.831,
    'Southwest Airlines': 0.804,
    'Alaska Airlines': 0.82,
    'JetBlue Airways': 0.81,
    'Spirit Airlines': 0.79,
    'Frontier Airlines': 0.78,
    'Allegiant Air': 0.77,
    'Hawaiian Airlines': 0.83,
    'Air Canada': 0.82,
    'WestJet': 0.81,
    'Air Transat': 0.78,
    'Flair Airlines': 0.76,
    'Porter Airlines': 0.79,
    'Aeroméxico': 0.79,
    'Volaris': 0.82,
    'VivaAerobus': 0.80,
    'Aeromar': 0.77,
    'LATAM Airlines': 0.81,
    'Avianca': 0.80,
    'Gol Linhas Aéreas': 0.82,
    'Azul Brazilian Airlines': 0.83,
    'Aerolíneas Argentinas': 0.78,
    'Sky Airline': 0.77,
    'JetSmart': 0.76,
    'Viva Air Colombia': 0.75,
    'Paranair': 0.74,
    'Conviasa': 0.65,
    'Air China': 0.81,
    'China Eastern Airlines': 0.80,
    'China Southern Airlines': 0.79,
    'Hainan Airlines': 0.83,
    'Shenzhen Airlines': 0.78,
    'All Nippon Airways (ANA)': 0.84,
    'Japan Airlines': 0.84,
    'Peach Aviation': 0.79,
    'Skymark Airlines': 0.78,
    'Jetstar Japan': 0.77,
    'Korean Air': 0.83,
    'Asiana Airlines': 0.82,
    'Jeju Air': 0.80,
    'T\'way Air': 0.79,
    'Jin Air': 0.78,
    'IndiGo': 0.85,
    'Air India': 0.78,
    'Vistara': 0.81,
    'SpiceJet': 0.80,
    'Go First': 0.77,
    'Singapore Airlines': 0.85,
    'Scoot': 0.80,
    'Malaysia Airlines': 0.78,
    'AirAsia': 0.79,
    'Firefly': 0.75,
    'Thai Airways': 0.77,
    'Bangkok Airways': 0.76,
    'Thai AirAsia': 0.79,
    'Vietnam Airlines': 0.81,
    'VietJet Air': 0.80,
    'Philippine Airlines': 0.78,
    'Cebu Pacific': 0.79,
    'Garuda Indonesia': 0.78,
    'Lion Air': 0.80,
    'Batik Air': 0.79,
    'Citilink': 0.78,
    'Cathay Pacific': 0.82,
    'Hong Kong Airlines': 0.79,
    'HK Express': 0.78,
    'China Airlines': 0.81,
    'EVA Air': 0.84,
    'Starlux Airlines': 0.83,
    'Air Macau': 0.75,
    'Biman Bangladesh Airlines': 0.74,
    'US-Bangla Airlines': 0.73,
    'Novoair': 0.72,
    'Pakistan International Airlines': 0.70,
    'Airblue': 0.69,
    'SereneAir': 0.71,
    'Air Astana': 0.79,
    'SCAT Airlines': 0.70,
    'MIAT Mongolian Airlines': 0.73,
    'Hunnu Air': 0.72,
    'Cambodia Angkor Air': 0.74,
    'Lanmei Airlines': 0.72,
    'Lao Airlines': 0.73,
    'Myanmar National Airlines': 0.71,
    'Air KBZ': 0.70,
    'Nepal Airlines': 0.69,
    'Himalaya Airlines': 0.70,
    'SriLankan Airlines': 0.78,
    'Ariana Afghan Airlines': 0.65,
    'Kam Air': 0.68,
    'Somon Air': 0.70,
    'Uzbekistan Airways': 0.73,
    'Turkmenistan Airlines': 0.68,
    'Azerbaijan Airlines': 0.74,
    'Lufthansa': 0.84,
    'British Airways': 0.83,
    'Air France': 0.82,
    'KLM Royal Dutch Airlines': 0.82,
    'Ryanair': 0.90,
    'easyJet': 0.88,
    'Turkish Airlines': 0.84,
    'Swiss International Air Lines': 0.83,
    'SAS Scandinavian Airlines': 0.81,
    'Alitalia (now ITA Airways)': 0.78,
    'TAP Air Portugal': 0.81,
    'Finnair': 0.82,
    'Aer Lingus': 0.81,
    'Wizz Air': 0.87,
    'Norwegian Air Shuttle': 0.85,
    'Brussels Airlines': 0.80,
    'Austrian Airlines': 0.82,
    'LOT Polish Airlines': 0.80,
    'Iberia': 0.82,
    'Vueling Airlines': 0.81,
    'Qantas Airways': 0.84,
    'Virgin Australia': 0.82,
    'Jetstar Airways': 0.80,
    'Air New Zealand': 0.84,
    'Fiji Airways': 0.78,
    'Air Niugini': 0.73,
    'Air Vanuatu': 0.72,
    'Aircalin': 0.74,
    'Air Tahiti Nui': 0.77,
    'Air Tahiti': 0.75,
    'Solomon Airlines': 0.70,
    'Air Kiribati': 0.68,
    'Nauru Airlines': 0.67,
    'Samoa Airways': 0.70,
    'Air Rarotonga': 0.71,
    'Norfolk Air': 0.65,
    'Air Marshall Islands': 0.68,
    'Palau Pacific Airways': 0.69,
    'Real Tonga': 0.68,
    'Northern Mariana Airways': 0.65
}

# The Airline Name ➔ ICAO Code mapping
airline_name_to_icao = {
    'Ethiopian Airlines': 'ETH',
    'EgyptAir': 'MSR',
    'South African Airways': 'SAA',
    'Kenya Airways': 'KQA',
    'Royal Air Maroc': 'RAM',
    'Air Algérie': 'DAH',
    'Tunisair': 'TAR',
    'Air Mauritius': 'MAU',
    'Air Peace': 'APK',
    'RwandAir': 'RWD',
    'Air Tanzania': 'ATC',
    'FlySafair': 'SFR',
    'Africa World Airlines': 'AFW',
    'Libyan Airlines': 'LAA',
    'Air Côte d\'Ivoire': 'VRE',
    'TAAG Angola Airlines': 'DTA',
    'Air Senegal': 'SGG',
    'Airlink': 'LNK',
    'Fastjet': 'FJW',
    'Nile Air': 'NIA',
    'American Airlines': 'AAL',
    'Delta Air Lines': 'DAL',
    'United Airlines': 'UAL',
    'Southwest Airlines': 'SWA',
    'Alaska Airlines': 'ASA',
    'JetBlue Airways': 'JBU',
    'Spirit Airlines': 'NKS',
    'Frontier Airlines': 'FFT',
    'Allegiant Air': 'AAY',
    'Hawaiian Airlines': 'HAL',
    'Air Canada': 'ACA',
    'WestJet': 'WJA',
    'Air Transat': 'TSC',
    'Flair Airlines': 'FLE',
    'Porter Airlines': 'POE',
    'Aeroméxico': 'AMX',
    'Volaris': 'VOI',
    'VivaAerobus': 'VIV',
    'Aeromar': 'TAO',
    'LATAM Airlines': 'LAN',
    'Avianca': 'AVA',
    'Gol Linhas Aéreas': 'GLO',
    'Azul Brazilian Airlines': 'AZU',
    'Aerolíneas Argentinas': 'ARG',
    'Sky Airline': 'SKU',
    'JetSmart': 'JAT',
    'Viva Air Colombia': 'VVC',
    'Paranair': 'AZP',
    'Conviasa': 'VCV',
    'Air China': 'CCA',
    'China Eastern Airlines': 'CES',
    'China Southern Airlines': 'CSN',
    'Hainan Airlines': 'CHH',
    'Shenzhen Airlines': 'CSZ',
    'All Nippon Airways (ANA)': 'ANA',
    'Japan Airlines': 'JAL',
    'Peach Aviation': 'APJ',
    'Skymark Airlines': 'SKY',
    'Jetstar Japan': 'JJP',
    'Korean Air': 'KAL',
    'Asiana Airlines': 'AAR',
    'Jeju Air': 'JJA',
    'T\'way Air': 'TWB',
    'Jin Air': 'JNA',
    'IndiGo': 'IGO',
    'Air India': 'AIC',
    'Vistara': 'VTI',
    'SpiceJet': 'SEJ',
    'Go First': 'GOW',
    'Singapore Airlines': 'SIA',
    'Scoot': 'TGW',
    'Malaysia Airlines': 'MAS',
    'AirAsia': 'AXM',
    'Firefly': 'FFM',
    'Thai Airways': 'THA',
    'Bangkok Airways': 'BKP',
    'Thai AirAsia': 'AIQ',
    'Vietnam Airlines': 'HVN',
    'VietJet Air': 'VJC',
    'Philippine Airlines': 'PAL',
    'Cebu Pacific': 'CEB',
    'Garuda Indonesia': 'GIA',
    'Lion Air': 'LNI',
    'Batik Air': 'BTK',
    'Citilink': 'CTV',
    'Cathay Pacific': 'CPA',
    'Hong Kong Airlines': 'CRK',
    'HK Express': 'HKE',
    'China Airlines': 'CAL',
    'EVA Air': 'EVA',
    'Starlux Airlines': 'SJX',
    'Air Macau': 'AMU',
    'Biman Bangladesh Airlines': 'BBC',
    'US-Bangla Airlines': 'UBG',
    'Novoair': 'NVQ',
    'Pakistan International Airlines': 'PIA',
    'Airblue': 'ABQ',
    'SereneAir': 'SEP',
    'Air Astana': 'KZR',
    'SCAT Airlines': 'VSV',
    'MIAT Mongolian Airlines': 'MGL',
    'Hunnu Air': 'MML',
    'Cambodia Angkor Air': 'KHV',
    'Lanmei Airlines': 'MKR',
    'Lao Airlines': 'LAO',
    'Myanmar National Airlines': 'UBA',
    'Air KBZ': 'KBZ',
    'Nepal Airlines': 'RNA',
    'Himalaya Airlines': 'HIM',
    'SriLankan Airlines': 'ALK',
    'Ariana Afghan Airlines': 'AFG',
    'Kam Air': 'KMF',
    'Somon Air': 'SMR',
    'Uzbekistan Airways': 'UZB',
    'Turkmenistan Airlines': 'TUA',
    'Azerbaijan Airlines': 'AHY',
    'Lufthansa': 'DLH',
    'British Airways': 'BAW',
    'Air France': 'AFR',
    'KLM Royal Dutch Airlines': 'KLM',
    'Ryanair': 'RYR',
    'easyJet': 'EZY',
    'Turkish Airlines': 'THY',
    'Swiss International Air Lines': 'SWR',
    'SAS Scandinavian Airlines': 'SAS',
    'Alitalia (now ITA Airways)': 'ITY',
    'TAP Air Portugal': 'TAP',
    'Finnair': 'FIN',
    'Aer Lingus': 'EIN',
    'Wizz Air': 'WZZ',
    'Norwegian Air Shuttle': 'NAX',
    'Brussels Airlines': 'BEL',
    'Austrian Airlines': 'AUA',
    'LOT Polish Airlines': 'LOT',
    'Iberia': 'IBE',
    'Vueling Airlines': 'VLG',
    'Qantas Airways': 'QFA',
    'Virgin Australia': 'VOZ',
    'Jetstar Airways': 'JST',
    'Air New Zealand': 'ANZ',
    'Fiji Airways': 'FJI',
    'Air Niugini': 'ANG',
    'Air Vanuatu': 'AVN',
    'Aircalin': 'ACI',
    'Air Tahiti Nui': 'THT',
    'Air Tahiti': 'VTA',
    'Solomon Airlines': 'SOL',
    'Air Kiribati': 'AKL',
    'Nauru Airlines': 'RON',
    'Samoa Airways': 'PAO',
    'Air Rarotonga': 'RAR',
    'Norfolk Air': 'NFA',
    'Air Marshall Islands': 'MRS',
    'Palau Pacific Airways': 'PPA',
    'Real Tonga': 'RLT',
    'Northern Mariana Airways': 'NMA'
}

# Step 1: Build a new dictionary using ICAO codes
loadFactorICAO = {}

for airline_name, factor in loadFactor.items():
    icao_code = airline_name_to_icao.get(airline_name)
    if icao_code:
        loadFactorICAO[icao_code] = factor
    else:
        print(f"Warning: No ICAO code found for {airline_name}")

# Step 2: Done! Now loadFactorICAO uses ICAO codes as keys
with open('loadFactorICAO.json', 'w') as f:
    json.dump(loadFactorICAO, f, indent=4)